import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextLink from "next/link";
import { DesktopNav, MobileNav } from "@/components/Nav";
import { Typography } from "@/components/Typography";

export const contact = [
  {
    icon: "icon-[tabler--brand-discord-filled]",
    label: "Discord",
    link: "https://discord.com/users/1079117717090611260",
  },
  {
    icon: "icon-[tabler--brand-threads]",
    label: "Threads",
    link: "https://www.threads.net/@pyyupsk_",
  },
  {
    icon: "icon-[tabler--brand-mailgun]",
    label: "Email",
    link: "mailto:badend777@proton.me",
  },
];

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>
        <div className="flex h-screen max-w-[100vw] flex-col overflow-x-hidden">
          <header className="sticky left-0 top-0 z-10 min-h-[80px] w-full border-b bg-background/80 backdrop-blur-md">
            <div className="container flex h-full items-center justify-between">
              <NextLink href="/" aria-label="BadEnd">
                <Typography.H1>Magnus Reeves</Typography.H1>
              </NextLink>
              <DesktopNav />
              <MobileNav />
            </div>
          </header>
          <main className={`container flex-1 space-y-10`}>{children}</main>
          <footer className="w-full border-t bg-background">
            <div className="container flex h-full flex-col items-center justify-between space-y-2 py-4 md:flex-row md:space-y-0">
              <div className="flex flex-col items-center space-y-2 md:items-start">
                <p>
                  &copy; {new Date().getFullYear()} BadEnd, All Rights Reserved
                </p>
                <p>
                  This website is open source.{" "}
                  <NextLink
                    href="https://github.com/BadEnd777/Portfolio-Website"
                    target="_blank"
                    className="link"
                    aria-label="GitHub repository"
                  >
                    View on GitHub
                  </NextLink>
                </p>
              </div>
              <div className="flex space-x-4">
                {contact.map((item) => (
                  <NextLink
                    key={item.link}
                    href={item.link}
                    target="_blank"
                    rel="noopener noreferrer"
                    aria-label={item.label}
                  >
                    <span className={`${item.icon} size-6`} />
                  </NextLink>
                ))}
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
